version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Persist SQLite database
    environment:
      DATABASE_URL: "jdbc:sqlite:/app/data/email_processor.db"
